### ISSUE TITLE
"Warning: Cannot call a namespace ('$') Use --force to continue." when I run grunt.

### ISSUE THREAD

**Issue by thatpaulschofield** [cuthbertLab/music21j#20]
When I run grunt, I get the following error message:

Running "rollup:files" (rollup) task
Warning: Cannot call a namespace ('$') Use --force to continue.

Aborted due to warnings.

**Comment by thatpaulschofield** [comment]
I run grunt --force and get this: 

Running "rollup:files" (rollup) task
Warning: Cannot call a namespace ('$') Used --force, continuing.

Then I run python start_python_server.py to start the web server. When I pull up any of the pages under testHtml, I get 404 errors on many of the javascript files under /src/ext/jsonpickle/ and /src/ext/midijs/

**Comment by thatpaulschofield** [comment]
I'm a bit of a noob on the Mac, so I certainly could have hosed something up.

**Comment by mscuthbert** [comment]
Did you run "npm install" first?  I don't know why '$' wouldn't be an acceptable namespace.  It might be an older version of some of the software on your system?  Sorry that I'm a big of a NOOB when it comes to running grunt and rollup, so don't have any ideas immediately come to mind.

**Comment by thatpaulschofield** [comment]
OK, I pulled down a fresh copy in case I had jacked anything up. 

First thing I do is an "npm install" and everything seems to go smoothly until this:

npm WARN grunt-contrib-cssmin@0.6.1 requires a peer of grunt@~0.4.0 but none was installed.

Here's the grunt version:

unknownf45c89a32441:music21j paulschofield$ npm show grunt version
1.0.1

**Comment by remon-georgy** [comment]
@thatpaulschofield I guess the issue is a version mismatch between required grunt (0.4.0) and your globally installed version (1.0.1).

Generally, I find it easier to manage js projects if I remove ALL global npm packages. Then let each project download required packages locally via `npm install`.

WIth that being said, I think music21j's package.json could be updated with latest package versions, too.

**Comment by thatpaulschofield** [comment]
Awesome, I'll try that out. Thanks for taking the time to help me out, Michael.

**Comment by mscuthbert** [comment]
I get a bunch of warnings on version mismatch of grunt also when I install, but I think it works fine.  I think it's some interior package requirings a lower version of grunt that what most of us have installed (but working fine with it).

@remon-georgy -- if you can submit a patch, I'd be glad to have it.  I'm mostly a python person -- I can program well in Javascript now, but I don't know anything about the npm / grunt / rollup world.

(actually, my plan was to use webpack, but I coulnd't get it to work...)

**Comment by remon-georgy** [comment]
@mscuthbert I agree that js packaging could be painful. I'm not a master myself, I just tried to use webpack in order to bundle music21j for a React project. Needless to say I failed miserably, mostly because music21j is using AMD internally. 

Although I'm not entirely sure how to package music21j better, CommonJS looks more future proof and plays will the rest of js ecosystem, way better than AMD. I'll see if I can work on that soon.

**Comment by mscuthbert** [comment]
Hi @remon-georgy -- it might be much easier to do now that music21j is entirely using ES6 modules in the codebase which is way easier to refactor into anything else.  The big problem that I've run into that I could use huge help on since I haven't found anything doing this on the web is that I'd like to rollup all the music21j sources into one file BUT still use JQuery, Vexflow, and MIDIjs as external files (I don't want to roll them into the same code -- otherwise it gets huge and unmaintainable and any small change requires redownloading a large piece of code).   The switch from AMD to CommonJS in itself wouldn't be enough to encourage me to switch over (since there's a good amount of code in the wild wanting music21j to be AMD), but being able to do a <script src="music21j.js"> and getting all the subrequirements loaded along the way -- now THAT would be worthwhile!

**Comment by mscuthbert** [comment]
Is this issue still a problem?  Thanks!

**Comment by mscuthbert** [comment]
If you replace the "import * as $ from 'jquery'" with "import $ from 'jquery'" it might go away?  I've now seen this error in other projects.  I haven't made the change in music21j yet, since it seems to work well enough for me.

**Comment by mscuthbert** [comment]
My guess is that this is no longer a problem with Webpack -- reopen if it is.
